apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client-v2
  labels:
    app: my-client-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-client
      version: v2
  template:
    metadata:
      labels:
        app: my-client
        version: v2
    spec:
      containers:
        - name: my-client-v2
          image: quay.io/vinamra2807/social-client:3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BASE_URL
              value: "$(route)"
